import { useState } from 'react';
import Head from 'next/head'
import groq from 'groq'
import styles from '../styles/Home.module.css'
import sanityClient from "../client.js";
import  Link  from 'next/link';




const Home = ({posts}) => {

  const [query, setQuery] = useState("");


  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptocheck24</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" />
      </Head>

      {/* search form */}
      <div className='pb-10'>
      <form className='pt-40 lg:px-40'>
        <div className='flex flex-col justify-center items-center pb-3 text-gray-700 text-center'>
            <h2 className='text-4xl font-semibold'>Wer akzeptiert Crypto im Jahr 2022?</h2>
            <p>Finde alle Unternehmen in deiner Nähe und bezahle mit Bitcoin, Ethereum und co.</p>
        </div>   
        <div className="relative">
            <div className="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                <svg aria-hidden="true" className="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
            </div>
            
            <input onChange={(e) => setQuery(e.target.value)} type="search" id="default-search" className="focus:outline-none focus:shadow-xl block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white" placeholder="Beispiel: Zimmermann AG" autoCapitalize='none' />
            {/* <button type="submit" className="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Suchen</button> */}
        </div>
      </form>
      </div>

      <div className='pb-28'>
      {posts.filter((post) =>
      post.title.toLowerCase().includes(query)
      ).map (
          ({ _id, title, description, slug }) =>
            slug && (
              <div key={_id} className='block pt-4 lg:px-40 w-full'>
                <Link href="/post/[slug]" as={`/post/${slug.current}`}>
                  <h2 className='text-blue-700 hover:text-blue-800 text-xl cursor-pointer'>{title}</h2>
                </Link>
                <p className='pb-4'>{description}</p>
                <hr></hr>
              </div>
            )
        )}
        </div>
    </div>
  )
}

export async function getStaticProps() {
  const posts = await sanityClient.fetch(groq `
  *[_type == "post"]
  `)
  return {
    props: {
      posts
    },
    revalidate: 10,
  }
}

export default Home